# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 3.0"
gem "puma", "~> 6.2"
gem "spackle-ruby", "~> 0.0.11"
gem "dotenv", "~> 2.8"
gem "sinatra-contrib", "~> 3.0"
